using System;

// Token: 0x02000197 RID: 407
public struct WindowPrefabData
{
	// Token: 0x060005D3 RID: 1491 RVA: 0x00080264 File Offset: 0x0007E464
	public WindowPrefabData(string n, Type t, string o = null)
	{
		this.m_PrefabName = n;
		this.m_WindowType = t;
		this.m_OptName = o;
	}

	// Token: 0x0400179C RID: 6044
	public string m_PrefabName;

	// Token: 0x0400179D RID: 6045
	public Type m_WindowType;

	// Token: 0x0400179E RID: 6046
	public string m_OptName;

	// Token: 0x0400179F RID: 6047
	public static readonly WindowPrefabData[] Data = new WindowPrefabData[]
	{
		new WindowPrefabData("UIOrigin", typeof(Door), null),
		new WindowPrefabData("UIBattle", typeof(UIBattle), null),
		new WindowPrefabData("UIStageInfo", typeof(UIStageInfo), null),
		new WindowPrefabData("UIStageStory", typeof(UIStageStory), null),
		new WindowPrefabData("UIStageSelect", typeof(UIStageSelect), "UIStageSelect"),
		new WindowPrefabData("UIStageSelect", typeof(UIStageSelect2), "UIStageSelect2"),
		new WindowPrefabData("UISettlement", typeof(UISettlement), null),
		new WindowPrefabData("UIHeroList", typeof(UIHeroList), "UIHeroList"),
		new WindowPrefabData("UIBattleHeroSelect", typeof(UIBattleHeroSelect), null),
		new WindowPrefabData("UIHero_Info", typeof(UIHero_Info), "UIHero_Info"),
		new WindowPrefabData("UIBattleReport", typeof(UIBattleReport), "UIBattleReport"),
		new WindowPrefabData("UIResourceBuilding", typeof(UIResourceBuilding), null),
		new WindowPrefabData("UISuitBuilding", typeof(UISuitBuilding), null),
		new WindowPrefabData("UIBagAndFilter", typeof(UIBagFilter), "UIBagShop"),
		new WindowPrefabData("UIChat", typeof(UIChat), null),
		new WindowPrefabData("UIHeroList_Soldier", typeof(UIHeroList_Soldier), null),
		new WindowPrefabData("UIBarrack", typeof(UIBarrack), null),
		new WindowPrefabData("UIBarrack_Soldier", typeof(UIBarrack_Soldier), null),
		new WindowPrefabData("UIHospital", typeof(UIHospital), null),
		new WindowPrefabData("UIExpedition", typeof(UIExpedition), "UIExpedition"),
		new WindowPrefabData("UIBagAndFilter", typeof(UIBookMark), "UIBookMark"),
		new WindowPrefabData("UIAllianceHint", typeof(AllianceHint), null),
		new WindowPrefabData("UIAllianceInput", typeof(InputBox), null),
		new WindowPrefabData("UIAlliance_Info", typeof(UILanguageSelect), "UILanguageSelect"),
		new WindowPrefabData("UISynthesis", typeof(UISynthesis), null),
		new WindowPrefabData("UIAlliance_Info", typeof(UIAlliance_List), "UIAlliance_List"),
		new WindowPrefabData("UIAlliance_Info", typeof(UIAlliance_Permission), "UIAlliance_Permission"),
		new WindowPrefabData("UIAlliance_Info", typeof(UIAlliance_Info), "UIAlliance_Info"),
		new WindowPrefabData("UIAlliance_Info", typeof(UIAlliance_publicinfo), "UIAlliance_publicinfo"),
		new WindowPrefabData("UIAlliance_Info", typeof(UIAlliance_Badge), "UIAlliance_Badge"),
		new WindowPrefabData("UIWarehouse", typeof(UIWarehouse), null),
		new WindowPrefabData("UIWatchtower", typeof(UIWatchtower), null),
		new WindowPrefabData("UIWatchtower_Details", typeof(UIWatchtower_Details), null),
		new WindowPrefabData("UIDevelopmentDetails", typeof(UIDevelopmentDetails), null),
		new WindowPrefabData("UILegBattle", typeof(UILegBattle), null),
		new WindowPrefabData("UI_leadup", typeof(UI_leadup), null),
		new WindowPrefabData("UIBattleReport", typeof(UI_NewTerritory), "UI_NewTerritory"),
		new WindowPrefabData("UIAlliance_Management", typeof(UIAlliance_Management), null),
		new WindowPrefabData("UIHeroUse", typeof(UIHeroUse), null),
		new WindowPrefabData("UIArmyInfo", typeof(UIArmyInfo), null),
		new WindowPrefabData("UI_Information", typeof(UIInformation), null),
		new WindowPrefabData("UITechTree", typeof(UITechTree), "UITechTree"),
		new WindowPrefabData("UITechTree", typeof(UITechInstitute), "UITechInstitute"),
		new WindowPrefabData("UITechTree", typeof(UITechUpgrade), "UITechUpgrade"),
		new WindowPrefabData("UILetter", typeof(UILetter), "UILetter"),
		new WindowPrefabData("UICityWall", typeof(UICityWall), null),
		new WindowPrefabData("UIMarket", typeof(UIMarket), null),
		new WindowPrefabData("UIMarket_Help", typeof(UIMarket_Help), null),
		new WindowPrefabData("UIEmbassy", typeof(UIEmbassy), null),
		new WindowPrefabData("UIFightingSummary", typeof(UIFightingSummary), "UIFightingSummary"),
		new WindowPrefabData("UIFightingSummary_Info", typeof(UIFightingSummary_Info), null),
		new WindowPrefabData("UILetter_Watchtower", typeof(UILetter_Watchtower), "UILetter_Watchtower"),
		new WindowPrefabData("UILetterEditor", typeof(UILetterEditor), null),
		new WindowPrefabData("UIDefenders", typeof(UIDefenders), null),
		new WindowPrefabData("UILetterDetail", typeof(UILetterDetail), null),
		new WindowPrefabData("UIWarLobby", typeof(UIWarLobby), null),
		new WindowPrefabData("UIWallRepair", typeof(UIWallRepair), null),
		new WindowPrefabData("UIAlliance_Info", typeof(UIAlliance_Rally), "UIAlliance_Rally"),
		new WindowPrefabData("UITrap", typeof(UITrap), null),
		new WindowPrefabData("UIExpedition", typeof(UIHeroList_Soldier2), "UIHeroList_Soldier2"),
		new WindowPrefabData("UICastle", typeof(UICastle), null),
		new WindowPrefabData("UICastleUpgradeReward", typeof(UICastleUpgradeReward), null),
		new WindowPrefabData("UILetter_Resources", typeof(UILetter_Resources), "UILetter_Resources"),
		new WindowPrefabData("UILetter_Resources", typeof(UILetter_Collection), "UILetter_Collection"),
		new WindowPrefabData("UIAlliance_Info", typeof(UIAlliance_HelpSpeedup), "UIAlliance_HelpSpeedup"),
		new WindowPrefabData("UIReplaceLord", typeof(UIReplaceLord), null),
		new WindowPrefabData("UI_LordInfo", typeof(UILordInfo), "UI_LordInfo"),
		new WindowPrefabData("UIBuffList", typeof(UIBuffList), "UIBuffList"),
		new WindowPrefabData("UIForge", typeof(UIForge), null),
		new WindowPrefabData("UITalent", typeof(UITalent), "UITalentTree"),
		new WindowPrefabData("UIActivity", typeof(UIActivity1), "UIActivity1"),
		new WindowPrefabData("UIActivity2", typeof(UIActivity2), "UIActivity2"),
		new WindowPrefabData("UIActivity3", typeof(UIActivity3), "UIActivity3"),
		new WindowPrefabData("UIActivity", typeof(UIActivity4), "UIActivity4"),
		new WindowPrefabData("UIMall", typeof(UIMall), "UIMall"),
		new WindowPrefabData("UIMall", typeof(UIMall_Detail), "UIMall_Detail"),
		new WindowPrefabData("UI_OpenBox", typeof(UIOpenBox), null),
		new WindowPrefabData("UISearchList", typeof(UISearchList), null),
		new WindowPrefabData("UIOther", typeof(UIOther), "UIOther"),
		new WindowPrefabData("UI_VIP", typeof(UIVIP), null),
		new WindowPrefabData("UIMission", typeof(UIMission), null),
		new WindowPrefabData("UI_HeroTalk", typeof(UIHeroTalk), null),
		new WindowPrefabData("UIOther", typeof(UIOther_FunctionSwitch), "UIOther_FunctionSwitch"),
		new WindowPrefabData("UIOther", typeof(UIOther_Forum), "UIOther_Forum"),
		new WindowPrefabData("UIOther", typeof(UIOther_Set), "UIOther_Set"),
		new WindowPrefabData("UIAltar", typeof(UIAltar), null),
		new WindowPrefabData("UI_Jail", typeof(UIJail), null),
		new WindowPrefabData("UI_JailMoney", typeof(UIJailMoney), null),
		new WindowPrefabData("UI_JailRoom", typeof(UIJailRoom), null),
		new WindowPrefabData("UIChapterRewards", typeof(UIChapterRewards), null),
		new WindowPrefabData("UI_LordEquip", typeof(UILordEquip), null),
		new WindowPrefabData("UI_EffectFilter", typeof(UIEffectFilter), null),
		new WindowPrefabData("UIForge_Item", typeof(UIForge_Item), "UIForge_Item"),
		new WindowPrefabData("UIForge_Item", typeof(UIForge_ActivityItem), "UIForge_ActivityItem"),
		new WindowPrefabData("UIOther_Account", typeof(UIOther_Account), null),
		new WindowPrefabData("UITBWindow", typeof(UITreasureBox), "UITreasureBox"),
		new WindowPrefabData("UI_ForgeAnvil", typeof(UIAnvil), null),
		new WindowPrefabData("UI_PriestTalk", typeof(UIPriestTalk), null),
		new WindowPrefabData("UI_Crypt", typeof(UICrypt), "UI_CryptBuild"),
		new WindowPrefabData("UI_Crypt", typeof(UICryptDig), "UI_CryptDig"),
		new WindowPrefabData("UI_VIPLevelUP", typeof(UIVIPLevelUP), null),
		new WindowPrefabData("UI_LeaderBoard", typeof(UILeaderBoard), null),
		new WindowPrefabData("UIBlackList", typeof(UIBlackList), null),
		new WindowPrefabData("UIMapMonster", typeof(UIMapMonster), "UIWorldMonster"),
		new WindowPrefabData("UIMapMonster", typeof(UIMonsterInfo), "UIMonsterInfo"),
		new WindowPrefabData("UIAlliance_Gift", typeof(UIAlliance_Gift), null),
		new WindowPrefabData("UIMessageBoard", typeof(UIMessageBoard), null),
		new WindowPrefabData("UIHeroUp", typeof(UIHeroUp), null),
		new WindowPrefabData("UIAnnouncement", typeof(UIAnnouncement), "UIAnnouncement"),
		new WindowPrefabData("UIArena", typeof(UIArena), "UIArena"),
		new WindowPrefabData("UIArena", typeof(UIArena_Replay), "UIArena_Replay"),
		new WindowPrefabData("UIArena", typeof(UIArena_Info), "UIArena_Info"),
		new WindowPrefabData("UIArena", typeof(UIArena_I), "UIArena_I"),
		new WindowPrefabData("UIWonderLand", typeof(UIWonderLand), "UIWonderLand"),
		new WindowPrefabData("UIWonderLand", typeof(UIWonderInfo), "UIWonderInfo"),
		new WindowPrefabData("UIMiniMap", typeof(UIMiniMap), "UIMiniMap"),
		new WindowPrefabData("UIFront", typeof(UIFront), null),
		new WindowPrefabData("UIName", typeof(UIName), null),
		new WindowPrefabData("UI_LordEquipSetEdit", typeof(UILordEquipSetEdit), null),
		new WindowPrefabData("UITalentSave", typeof(UITalentSave), null),
		new WindowPrefabData("UITalentSave", typeof(UISetSelect), null),
		new WindowPrefabData("UIKingdom_Classifieds", typeof(UIKingdom_Classifieds), null),
		new WindowPrefabData("UITitle", typeof(UITitle), null),
		new WindowPrefabData("UIPaySetting", typeof(UIPaySetting), null),
		new WindowPrefabData("UIAmbush", typeof(UIAmbush), null),
		new WindowPrefabData("UIMerchantman", typeof(UIMerchantman), null),
		new WindowPrefabData("UITalentSave", typeof(UITeamSave), null),
		new WindowPrefabData("UIBuffInformation", typeof(UIBuffInformation), null),
		new WindowPrefabData("UI_FormationSelect", typeof(UIFormationSelect), null),
		new WindowPrefabData("UIMall", typeof(UIRewardsSelect), "UIRewardsSelect"),
		new WindowPrefabData("UIAlliance_Mobilization", typeof(UIAlliance_Mobilization), "UIAlliance_Mobilization"),
		new WindowPrefabData("UIAlliance_Mobilization", typeof(UIAlliance_Mobilization_Info), "UIAlliance_Mobilization_Info"),
		new WindowPrefabData("UIWonderLand", typeof(UIWonderReward), "UIWonderReward"),
		new WindowPrefabData("UICanonizedPanel", typeof(UICanonizedPanel), null),
		new WindowPrefabData("UI_Immigration", typeof(UIImmigration), null),
		new WindowPrefabData("UI_LeaderBoard", typeof(UIKingdomVSLBoard), null),
		new WindowPrefabData("UI_LeaderBoard", typeof(UIKVKLBoard), null),
		new WindowPrefabData("UIBattle_Gambling", typeof(UIBattle_Gambling), null),
		new WindowPrefabData("UIAlchemy", typeof(UIAlchemy), null),
		new WindowPrefabData("UILetter_Watchtower", typeof(UILetter_NPCScout), "UILetter_Watchtower"),
		new WindowPrefabData("UIMonster_Crypt_3", typeof(UIMonster_Crypt_3), null),
		new WindowPrefabData("UIMonster_Crypt", typeof(UIMonsterCrypt), null),
		new WindowPrefabData("UITBWindow", typeof(UIChallegeTreasure), "UIChallegeReward"),
		new WindowPrefabData("UI_LeaderBoard", typeof(UIAlliHuntBoard), null),
		new WindowPrefabData("UIEmojiSelect", typeof(UIEmojiSelect), null),
		new WindowPrefabData("UIDonation", typeof(UIDonation), "UIDonation"),
		new WindowPrefabData("UIDonation", typeof(UIDonation_Info), "UIDonation_Info"),
		new WindowPrefabData("UIMapMonster", typeof(UISummonMonster), "UISummonMonster"),
		new WindowPrefabData("UISuicideBox", typeof(UISuicideBox), null),
		new WindowPrefabData("UICastleSkin", typeof(UICastleSkin), "UICastleSkinView"),
		new WindowPrefabData("UICastleSkin", typeof(UICastleStrengthen), "UICastleStrengthen"),
		new WindowPrefabData("UI_LeaderBoard", typeof(UINobilityBoard), null),
		new WindowPrefabData("UI_LeaderBoard", typeof(UINobilityOccupyBoard), null),
		new WindowPrefabData("UI_LordInfo", typeof(UIESportProfile), null),
		new WindowPrefabData("UILetter_Watchtower", typeof(UILetter_Watchtower_Recon), "UILetter_Watchtower_Recon"),
		new WindowPrefabData("UIFightingSummary", typeof(UIAlliance_FS), "UIFightingSummary"),
		new WindowPrefabData("UIFightingSummary_Info", typeof(UIAlliance_FS_Info), null),
		new WindowPrefabData("UIAllianceWarOver", typeof(UIAllianceWarOver), null),
		new WindowPrefabData("UI_LeaderBoard", typeof(UIAlliVSGroupBoard), null),
		new WindowPrefabData("UI_LeaderBoard", typeof(UIAlliVSAlliBoard), null),
		new WindowPrefabData("UIAllianceMatchInfo", typeof(UIAllianceMatchInfo), null),
		new WindowPrefabData("UI_AllianceWar_Register", typeof(UIAllianceWarRegister), null),
		new WindowPrefabData("UIAllianceWar_Rank", typeof(UIAllianceWar_Rank), null),
		new WindowPrefabData("UIAllianceBattle", typeof(UIAllianceWarBattle), null),
		new WindowPrefabData("UI_AlliWarSchedule", typeof(UI_AlliWarSchedule), null),
		new WindowPrefabData("UIMall", typeof(UIMall_FG), "UIMall_FG"),
		new WindowPrefabData("UIMall", typeof(UIMall_FG_Detail), "UIMall_FG_Detail"),
		new WindowPrefabData("UIPetFusionbuilding", typeof(UIPetFusionbuilding), null),
		new WindowPrefabData("UIPetFusion", typeof(UIPetFusion), null),
		new WindowPrefabData("UI_PetResourceStation", typeof(UI_PetResourceStation), null),
		new WindowPrefabData("UIFightingSummary", typeof(UIPetSkill_FS), "UIPetSkill_FS"),
		new WindowPrefabData("UIItemCraftShow", typeof(UIItemCraftShow), null),
		new WindowPrefabData("UIHeroList", typeof(UIPetBag), "UIPetBag"),
		new WindowPrefabData("UIPetList", typeof(UIPetList), null),
		new WindowPrefabData("UIPet", typeof(UIPet), "UIPet"),
		new WindowPrefabData("UIPet", typeof(UIPetStoneTrans), "UIPetStoneTrans"),
		new WindowPrefabData("UIPetBuff", typeof(UIPetBuff), null),
		new WindowPrefabData("UIPetBuff", typeof(UIPetSkill), "UIPetSkill"),
		new WindowPrefabData("UIPetBuff", typeof(UIPetBuff), "UIPetBuff"),
		new WindowPrefabData("UIExpedition", typeof(UIPetSelect), "UIPetSelect"),
		new WindowPrefabData("UIPetTrainingCenter", typeof(UIPetTrainingCenter), null),
		new WindowPrefabData("UITBWindow", typeof(UIPetLevelUp), "UIPetLevelUp"),
		new WindowPrefabData("UIAlliance_Info", typeof(UIAlliance_ActivityGift), "UIAlliance_ActivityGift"),
		new WindowPrefabData("UITBWindow", typeof(UITreasureBox_FB), "UITreasureBox_FB"),
		new WindowPrefabData("UIFBMission", typeof(UIFBWindow), "UIFBWindow"),
		new WindowPrefabData("UIMall", typeof(UIBackReward), "UIBackReward"),
		new WindowPrefabData("UIMall", typeof(UIBackReward_Detail), "UIBackReward_Detail"),
		new WindowPrefabData("UI_LeaderBoard", typeof(UIFootBallBoard), null),
		new WindowPrefabData("UIFootBall", typeof(UIFootBall), "UIFootBall"),
		new WindowPrefabData("UIFootBall", typeof(UIFootBallInfo), "UIFootBallInfo"),
		new WindowPrefabData("UI_LeaderBoard", typeof(UIAlliMobiWorldBoard), null),
		new WindowPrefabData("UIAlliance_Info", typeof(UILeaderboardReward), "UILeaderboardReward"),
		new WindowPrefabData("UIRating", typeof(UIRating), "UIRating"),
		new WindowPrefabData("UIShieldLog", typeof(UIShieldLog), "UIShieldLog"),
		new WindowPrefabData("UI_LeaderBoard", typeof(UIFootBallKVKBoard), null),
		new WindowPrefabData("UIMall", typeof(UIMall_FT), "UIMall_FT"),
		new WindowPrefabData("UIAnnouncement", typeof(UITermOfService), "UITermOfServices")
	};
}
